

CREATE SEQUENCE SEQ_CLI NOCACHE;
CREATE SEQUENCE SEQ_PDT NOCACHE;
CREATE SEQUENCE SEQ_SLV NOCACHE;
CREATE SEQUENCE SEQ_PLT NOCACHE;
CREATE SEQUENCE SEQ_COL NOCACHE;
CREATE SEQUENCE SEQ_CAR NOCACHE;
CREATE SEQUENCE SEQ_MAG NOCACHE;
CREATE SEQUENCE SEQ_MON NOCACHE;
CREATE SEQUENCE SEQ_XYZ NOCACHE;
CREATE SEQUENCE SEQ_NML NOCACHE;
CREATE SEQUENCE SEQ_PEN NOCACHE;








