

CREATE OR REPLACE TRIGGER TG_CLI
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
  :NEW.CLI_ID := APP.SEQ_CLI.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_PDT
BEFORE INSERT ON PRODUTOS
FOR EACH ROW
BEGIN
  :NEW.PDT_ID := APP.SEQ_PDT.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER TG_SLV
BEFORE INSERT ON SLEEVES
FOR EACH ROW
BEGIN
  :NEW.SLV_PDT_ID := APP.SEQ_SLV.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER TG_PLT
BEFORE INSERT ON PLAYMATCHS
FOR EACH ROW
BEGIN
  :NEW.PLT_PDT_ID := APP.SEQ_PLT.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER TG_COL
BEFORE INSERT ON COLECOES
FOR EACH ROW
BEGIN
  :NEW.COL_PDT_ID := APP.SEQ_COL.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER TG_CAR
BEFORE INSERT ON CARTAS
FOR EACH ROW
BEGIN
  :NEW.CAR_ID := APP.SEQ_CAR.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_MAG
BEFORE INSERT ON MAGICAS
FOR EACH ROW
BEGIN
  :NEW.MAG_CAR_ID := APP.SEQ_MAG.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_MON
BEFORE INSERT ON MONSTROS
FOR EACH ROW
BEGIN
  :NEW.MON_CAR_ID := APP.SEQ_MON.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_XYZ
BEFORE INSERT ON XYZS
FOR EACH ROW
BEGIN
  :NEW.XYZ_MON_ID := APP.SEQ_XYZ.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_NML
BEFORE INSERT ON NML_MONSTROS
FOR EACH ROW
BEGIN
  :NEW.NML_MON_ID := APP.SEQ_NML.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_PEN
BEFORE INSERT ON PENDULOS
FOR EACH ROW
BEGIN
  :NEW.PEN_CAR_MON_ID := APP.SEQ_PEN.NEXTVAL;
END;