
INSERT INTO SLEEVES(slv_marca, slv_pdt_id)
VALUES
    ('Ultra-Pro',1);

INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(321, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(322, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(323, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(324, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(325, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(326, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(327, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(328, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(329, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(330, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(331, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(332, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(333, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(334, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(335, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(336, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(337, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(338, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(339, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(340, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(341, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(342, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(343, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(344, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(345, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(346, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(347, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(348, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(349, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(350, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(351, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(352, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(353, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(354, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(355, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(356, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(357, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(358, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(359, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(360, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(361, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(362, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(363, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(364, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(365, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(366, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(367, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(368, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(369, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(370, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(371, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(372, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(373, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(374, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(375, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(376, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(377, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(378, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(379, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(380, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(381, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(382, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(383, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(384, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(385, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(386, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(387, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(388, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(389, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(390, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(391, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(392, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(393, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(394, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(395, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(396, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(397, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(398, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(399, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(400, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(401, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(402, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(403, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(404, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(405, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(406, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(407, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(408, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(409, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(410, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(411, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(412, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(413, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(414, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(415, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(416, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(417, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(418, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(419, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(420, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(421, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(422, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(423, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(424, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(425, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(426, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(427, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(428, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(429, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(430, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(431, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(432, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(433, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(434, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(435, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(436, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(437, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(438, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(439, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(440, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(441, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(442, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(443, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(444, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(445, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(446, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(447, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(448, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(449, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(450, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(451, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(452, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(453, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(454, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(455, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(456, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(457, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(458, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(459, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(460, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(461, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(462, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(463, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(464, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(465, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(466, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(467, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(468, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(469, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(470, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(471, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(472, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(473, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(474, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(475, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(476, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(477, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(478, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(479, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(480, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(481, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(482, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(483, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(484, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(485, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(486, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(487, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(488, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(489, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(490, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(491, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(492, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(493, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(494, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(495, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(496, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(497, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(498, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(499, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(500, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(501, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(502, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(503, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(504, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(505, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(506, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(507, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(508, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(509, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(510, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(511, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(512, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(513, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(514, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(515, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(516, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(517, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(518, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(519, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(520, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(521, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(522, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(523, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(524, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(525, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(526, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(527, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(528, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(529, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(530, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(531, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(532, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(533, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(534, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(535, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(536, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(537, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(538, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(539, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(540, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(541, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(542, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(543, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(544, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(545, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(546, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(547, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(548, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(549, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(550, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(551, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(552, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(553, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(554, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(555, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(556, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(557, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(558, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(559, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(560, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(561, 'ojama sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(562, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(563, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(564, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(565, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(566, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(567, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(568, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(569, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(570, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(571, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(572, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(573, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(574, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(575, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(576, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(577, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(578, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(579, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(580, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(581, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(582, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(583, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(584, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(585, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(586, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(587, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(588, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(589, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(590, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(591, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(592, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(593, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(594, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(595, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(596, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(597, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(598, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(599, 'wizard senior');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(600, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(601, 'Marcio 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(602, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(603, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(604, 'Lucas 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(605, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(606, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(607, 'KMC');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(608, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(609, '6 is 10');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(610, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(611, 'crystal dragon');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(612, 'fatec sleeve');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(613, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(614, 'Ultra Pro');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(615, 'Dragon shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(616, 'Mari the best teacher');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(617, 'Gabriel 4 MVP');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(618, 'konami shield');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(619, 'Elementar protect');
INSERT INTO SLEEVES(slv_pdt_id, slv_marca) VALUES(620, 'wizard senior');