
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' AtoZDragon Buster Cannon ' , ' LIGHT ' , ' Machine ' , ' teste3 ' , 1 , 608 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' ABCDragon Buster ' , ' LIGHT ' , ' Machine ' , ' teste4 ' , 2 , 609 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Alligators Sword Dragon ' , ' WIND ' , ' Dragon ' , ' teste5 ' , 3 , 610 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Amazoness Empress ' , ' EARTH ' , ' Warrior ' , ' teste6 ' , 4 , 611 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Amazoness Pet Liger ' , ' EARTH ' , ' Beast ' , ' teste7 ' , 5 , 612 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ambulance Rescueroid ' , ' FIRE ' , ' Machine ' , ' teste8 ' , 6 , 613 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Amphibious Bugroth ' , ' WATER ' , ' Aqua ' , ' teste9 ' , 7 , 614 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Amulet Dragon ' , ' DARK ' , ' Dragon ' , ' teste10 ' , 8 , 615 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ancient Gear Howitzer ' , ' EARTH ' , ' Machine ' , ' teste11 ' , 9 , 616 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ancient Gear Megaton Golem ' , ' EARTH ' , ' Machine ' , ' teste12 ' , 10 , 617 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Aqua Dragon ' , ' WATER ' , ' Sea Serpent ' , ' teste13 ' , 11 , 618 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Arcana Knight Joker ' , ' LIGHT ' , ' Warrior ' , ' teste14 ' , 12 , 619 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Archfiend Black Skull Dragon ' , ' DARK ' , ' Dragon ' , ' teste15 ' , 1 , 620 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Armed Dragon Catapult Cannon ' , ' LIGHT ' , ' Machine ' , ' teste16 ' , 2 , 621 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Armityle the Chaos Phantom ' , ' DARK ' , ' Fiend ' , ' teste17 ' , 3 , 622 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' B Skull Dragon ' , ' DARK ' , ' Dragon ' , ' teste18 ' , 4 , 623 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Barbaroid the Ultimate Battle Machine ' , ' EARTH ' , ' Machine ' , ' teste19 ' , 5 , 624 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Barox ' , ' DARK ' , ' Fiend ' , ' teste20 ' , 6 , 625 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' BeastEyes Pendulum Dragon ' , ' EARTH ' , ' Dragon ' , ' teste21 ' , 7 , 626 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Bickuribox ' , ' DARK ' , ' Fiend ' , ' teste22 ' , 8 , 627 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Blaze Fenix the Burning Bombardment Bird ' , ' FIRE ' , ' Pyro ' , ' teste23 ' , 9 , 628 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Bloom Diva the Melodious Choir ' , ' LIGHT ' , ' Fairy ' , ' teste24 ' , 10 , 629 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Bloom Prima the Melodious Choir ' , ' LIGHT ' , ' Fairy ' , ' teste25 ' , 11 , 630 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' BlueEyes Twin Burst Dragon ' , ' LIGHT ' , ' Dragon ' , ' teste26 ' , 12 , 631 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' BlueEyes Ultimate Dragon ' , ' LIGHT ' , ' Dragon ' , ' teste27 ' , 1 , 632 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Bracchioraidus ' , ' WATER ' , ' Dinosaur ' , ' teste28 ' , 2 , 633 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' BraveEyes Pendulum Dragon ' , ' DARK ' , ' Dragon ' , ' teste29 ' , 3 , 634 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Buster Blader the Dragon Destroyer Swordsman ' , ' LIGHT ' , ' Warrior ' , ' teste30 ' , 4 , 635 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Chaos Ancient Gear Giant ' , ' DARK ' , ' Machine ' , ' teste31 ' , 5 , 636 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Charubin the Fire Knight ' , ' FIRE ' , ' Pyro ' , ' teste32 ' , 6 , 637 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Chimera the Flying Mythical Beast ' , ' WIND ' , ' Beast ' , ' teste33 ' , 7 , 638 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Chimeratech Fortress Dragon ' , ' DARK ' , ' Machine ' , ' teste34 ' , 8 , 639 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Chimeratech Megafleet Dragon ' , ' DARK ' , ' Machine ' , ' teste35 ' , 9 , 640 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Chimeratech Overdragon ' , ' DARK ' , ' Machine ' , ' teste36 ' , 10 , 641 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Chimeratech Rampage Dragon ' , ' DARK ' , ' Machine ' , ' teste37 ' , 11 , 642 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Contrast HERO Chaos ' , ' DARK ' , ' Warrior ' , ' teste38 ' , 12 , 643 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Crimson Nova Trinity the Dark Cubic Lord ' , ' DARK ' , ' Fiend ' , ' teste39 ' , 1 , 644 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Crimson Sunbird ' , ' FIRE ' , ' Winged Beast ' , ' teste40 ' , 2 , 645 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Cyber Blader ' , ' EARTH ' , ' Warrior ' , ' teste41 ' , 3 , 646 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Cyber End Dragon ' , ' LIGHT ' , ' Machine ' , ' teste42 ' , 4 , 647 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Cyber Ogre 2 ' , ' EARTH ' , ' Machine ' , ' teste43 ' , 5 , 648 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Cyber Saurus ' , ' EARTH ' , ' Machine ' , ' teste44 ' , 6 , 649 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Cyber Twin Dragon ' , ' LIGHT ' , ' Machine ' , ' teste45 ' , 7 , 650 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Cyberdark Dragon ' , ' DARK ' , ' Machine ' , ' teste46 ' , 8 , 651 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Cyberdarkness Dragon ' , ' DARK ' , ' Dragon ' , ' teste47 ' , 9 , 652 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' D3S Frog ' , ' WATER ' , ' Aqua ' , ' teste48 ' , 10 , 653 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' D/D/D Dragonbane King Beowulf ' , ' DARK ' , ' Fiend ' , ' teste49 ' , 11 , 654 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' D/D/D Flame High King Executive Genghis ' , ' FIRE ' , ' Fiend ' , ' teste50 ' , 12 , 655 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' D/D/D Flame King Genghis ' , ' FIRE ' , ' Fiend ' , ' teste51 ' , 1 , 656 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' D/D/D Oracle King dArc ' , ' DARK ' , ' Fiend ' , ' teste52 ' , 2 , 657 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' D/D/D Superdoom King Purplish Armageddon ' , ' DARK ' , ' Fiend ' , ' teste53 ' , 3 , 658 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' D/D/D Wave Oblivion King Caesar Ragnarok ' , ' DARK ' , ' Fiend ' , ' teste54 ' , 4 , 659 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dante Pilgrim of the Burning Abyss ' , ' LIGHT ' , ' Fairy ' , ' teste55 ' , 5 , 660 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dark Balter the Terrible ' , ' DARK ' , ' Fiend ' , ' teste56 ' , 6 , 661 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dark Blade the Dragon Knight ' , ' DARK ' , ' Warrior ' , ' teste57 ' , 7 , 662 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dark Flare Knight ' , ' DARK ' , ' Warrior ' , ' teste58 ' , 8 , 663 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dark Magician Girl the Dragon Knight ' , ' DARK ' , ' Dragon ' , ' teste59 ' , 9 , 664 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dark Magician the Dragon Knight ' , ' DARK ' , ' Dragon ' , ' teste60 ' , 10 , 665 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dark Paladin ' , ' DARK ' , ' Spellcaster ' , ' teste61 ' , 11 , 666 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Darkfire Dragon ' , ' DARK ' , ' Dragon ' , ' teste62 ' , 12 , 667 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Deepsea Shark ' , ' WATER ' , ' Fish ' , ' teste63 ' , 1 , 668 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Destiny End Dragoon ' , ' DARK ' , ' Warrior ' , ' teste64 ' , 2 , 669 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Destiny HERO  Dangerous ' , ' DARK ' , ' Warrior ' , ' teste65 ' , 3 , 670 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Destiny HERO  Dusktopia ' , ' DARK ' , ' Warrior ' , ' teste66 ' , 4 , 671 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Destiny HERO  Dystopia ' , ' DARK ' , ' Warrior ' , ' teste67 ' , 5 , 672 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dinoster Power the Mighty Dracoslayer ' , ' WATER ' , ' Dragon ' , ' teste68 ' , 6 , 673 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Doom Virus Dragon ' , ' DARK ' , ' Dragon ' , ' teste69 ' , 7 , 674 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dragon Knight DracoEquiste ' , ' WIND ' , ' Dragon ' , ' teste70 ' , 8 , 675 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dragon Master Knight ' , ' LIGHT ' , ' Dragon ' , ' teste71 ' , 9 , 676 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dragonecro Nethersoul Dragon ' , ' DARK ' , ' Dragon ' , ' teste72 ' , 10 , 677 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Dragoness the Wicked Knight ' , ' WIND ' , ' Warrior ' , ' teste73 ' , 11 , 678 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' El Shaddoll Anoyatyllis ' , ' WATER ' , ' Fiend ' , ' teste74 ' , 12 , 679 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' El Shaddoll Construct ' , ' LIGHT ' , ' Fairy ' , ' teste75 ' , 1 , 680 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' El Shaddoll Grysta ' , ' FIRE ' , ' Rock ' , ' teste76 ' , 2 , 681 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' El Shaddoll Shekhinaga ' , ' EARTH ' , ' Machine ' , ' teste77 ' , 3 , 682 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' El Shaddoll Wendigo ' , ' WIND ' , ' Psychic ' , ' teste78 ' , 4 , 683 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' El Shaddoll Winda ' , ' DARK ' , ' Spellcaster ' , ' teste79 ' , 5 , 684 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elder Entity Ntss ' , ' LIGHT ' , ' Fairy ' , ' teste80 ' , 6 , 685 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elder Entity Norden ' , ' WATER ' , ' Fairy ' , ' teste81 ' , 7 , 686 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Absolute Zero ' , ' WATER ' , ' Warrior ' , ' teste82 ' , 8 , 687 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Air Neos ' , ' WIND ' , ' Warrior ' , ' teste83 ' , 9 , 688 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Aqua Neos ' , ' WATER ' , ' Warrior ' , ' teste84 ' , 10 , 689 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Chaos Neos ' , ' DARK ' , ' Warrior ' , ' teste85 ' , 11 , 690 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Core ' , ' EARTH ' , ' Warrior ' , ' teste86 ' , 12 , 691 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Dark Neos ' , ' DARK ' , ' Warrior ' , ' teste87 ' , 1 , 692 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Darkbright ' , ' DARK ' , ' Warrior ' , ' teste88 ' , 2 , 693 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Divine Neos ' , ' LIGHT ' , ' Warrior ' , ' teste89 ' , 3 , 694 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Electrum ' , ' LIGHT ' , ' Warrior ' , ' teste90 ' , 4 , 695 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Escuridao ' , ' DARK ' , ' Warrior ' , ' teste91 ' , 5 , 696 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Flame Wingman ' , ' WIND ' , ' Warrior ' , ' teste92 ' , 6 , 697 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Flare Neos ' , ' FIRE ' , ' Warrior ' , ' teste93 ' , 7 , 698 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Gaia ' , ' EARTH ' , ' Warrior ' , ' teste94 ' , 8 , 699 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Glow Neos ' , ' LIGHT ' , ' Warrior ' , ' teste95 ' , 9 , 700 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Grand Neos ' , ' EARTH ' , ' Warrior ' , ' teste96 ' , 10 , 701 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Great Tornado ' , ' WIND ' , ' Warrior ' , ' teste97 ' , 11 , 702 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Inferno ' , ' FIRE ' , ' Pyro ' , ' teste98 ' , 12 , 703 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Magma Neos ' , ' FIRE ' , ' Warrior ' , ' teste99 ' , 1 , 704 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Marine Neos ' , ' WATER ' , ' Warrior ' , ' teste100 ' , 2 , 705 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Mariner ' , ' WATER ' , ' Warrior ' , ' teste101 ' , 3 , 706 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Mudballman ' , ' EARTH ' , ' Warrior ' , ' teste102 ' , 4 , 707 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Necroid Shaman ' , ' DARK ' , ' Warrior ' , ' teste103 ' , 5 , 708 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Neos Knight ' , ' LIGHT ' , ' Warrior ' , ' teste104 ' , 6 , 709 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Nova Master ' , ' FIRE ' , ' Warrior ' , ' teste105 ' , 7 , 710 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Phoenix Enforcer ' , ' FIRE ' , ' Warrior ' , ' teste106 ' , 8 , 711 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Plasma Vice ' , ' EARTH ' , ' Warrior ' , ' teste107 ' , 9 , 712 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Rampart Blaster ' , ' EARTH ' , ' Warrior ' , ' teste108 ' , 10 , 713 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Shining Flare Wingman ' , ' LIGHT ' , ' Warrior ' , ' teste109 ' , 11 , 714 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Shining Phoenix Enforcer ' , ' FIRE ' , ' Warrior ' , ' teste110 ' , 12 , 715 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Steam Healer ' , ' WATER ' , ' Warrior ' , ' teste111 ' , 1 , 716 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Storm Neos ' , ' WIND ' , ' Warrior ' , ' teste112 ' , 2 , 717 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Tempest ' , ' WIND ' , ' Warrior ' , ' teste113 ' , 3 , 718 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Terra Firma ' , ' EARTH ' , ' Warrior ' , ' teste114 ' , 4 , 719 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO The Shining ' , ' LIGHT ' , ' Warrior ' , ' teste115 ' , 5 , 720 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Thunder Giant ' , ' LIGHT ' , ' Warrior ' , ' teste116 ' , 6 , 721 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Wild Wingman ' , ' EARTH ' , ' Warrior ' , ' teste117 ' , 7 , 722 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Elemental HERO Wildedge ' , ' EARTH ' , ' Warrior ' , ' teste118 ' , 8 , 723 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Empress Judge ' , ' EARTH ' , ' Warrior ' , ' teste119 ' , 9 , 724 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Evil HERO Dark Gaia ' , ' EARTH ' , ' Fiend ' , ' teste120 ' , 10 , 725 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Evil HERO Infernal Sniper ' , ' FIRE ' , ' Fiend ' , ' teste121 ' , 11 , 726 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Evil HERO Inferno Wing ' , ' FIRE ' , ' Fiend ' , ' teste122 ' , 12 , 727 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Evil HERO Lightning Golem ' , ' LIGHT ' , ' Fiend ' , ' teste123 ' , 1 , 728 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Evil HERO Malicious Fiend ' , ' FIRE ' , ' Fiend ' , ' teste124 ' , 2 , 729 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Evil HERO Wild Cyclone ' , ' EARTH ' , ' Fiend ' , ' teste125 ' , 3 , 730 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Fiend Skull Dragon ' , ' WIND ' , ' Dragon ' , ' teste126 ' , 4 , 731 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' First of the Dragons ' , ' DARK ' , ' Dragon ' , ' teste127 ' , 5 , 732 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' FiveHeaded Dragon ' , ' DARK ' , ' Dragon ' , ' teste128 ' , 6 , 733 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Flame Ghost ' , ' DARK ' , ' Zombie ' , ' teste129 ' , 7 , 734 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Flame Swordsman ' , ' FIRE ' , ' Warrior ' , ' teste130 ' , 8 , 735 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Flower Wolf ' , ' EARTH ' , ' Beast ' , ' teste131 ' , 9 , 736 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur Bear ' , ' DARK ' , ' Fiend ' , ' teste132 ' , 10 , 737 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur Chimera ' , ' DARK ' , ' Fiend ' , ' teste133 ' , 11 , 738 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur Daredevil ' , ' DARK ' , ' Fiend ' , ' teste134 ' , 12 , 739 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur Kraken ' , ' WATER ' , ' Fiend ' , ' teste135 ' , 1 , 740 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur Leo ' , ' DARK ' , ' Fiend ' , ' teste136 ' , 2 , 741 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur SabreTooth ' , ' DARK ' , ' Fiend ' , ' teste137 ' , 3 , 742 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur Sheep ' , ' DARK ' , ' Fiend ' , ' teste138 ' , 4 , 743 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur Tiger ' , ' DARK ' , ' Fiend ' , ' teste139 ' , 5 , 744 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Frightfur Wolf ' , ' DARK ' , ' Fiend ' , ' teste140 ' , 6 , 745 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Fullmetalfoes Alkahest ' , ' FIRE ' , ' Psychic ' , ' teste141 ' , 7 , 746 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Fusionist ' , ' EARTH ' , ' Beast ' , ' teste142 ' , 8 , 747 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gaia Drake the Universal Force ' , ' EARTH ' , ' Beast-Warrior ' , ' teste143 ' , 9 , 748 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gaia the Dragon Champion ' , ' WIND ' , ' Dragon ' , ' teste144 ' , 10 , 749 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gatling Dragon ' , ' DARK ' , ' Machine ' , ' teste145 ' , 11 , 750 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Amethyst ' , ' EARTH ' , ' Aqua ' , ' teste146 ' , 12 , 751 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Aquamarine ' , ' EARTH ' , ' Aqua ' , ' teste147 ' , 1 , 752 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Citrine ' , ' EARTH ' , ' Pyro ' , ' teste148 ' , 2 , 753 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Lady Brilliant Diamond ' , ' EARTH ' , ' Rock ' , ' teste149 ' , 3 , 754 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Lady Lapis Lazuli ' , ' EARTH ' , ' Rock ' , ' teste150 ' , 4 , 755 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Master Diamond ' , ' EARTH ' , ' Rock ' , ' teste151 ' , 5 , 756 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Prismaura ' , ' EARTH ' , ' Thunder ' , ' teste152 ' , 6 , 757 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Ruby ' , ' EARTH ' , ' Pyro ' , ' teste153 ' , 7 , 758 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Seraphinite ' , ' EARTH ' , ' Fairy ' , ' teste154 ' , 8 , 759 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Topaz ' , ' EARTH ' , ' Thunder ' , ' teste155 ' , 9 , 760 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' GemKnight Zirconia ' , ' EARTH ' , ' Rock ' , ' teste156 ' , 10 , 761 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Giltia the D Knight ' , ' LIGHT ' , ' Warrior ' , ' teste157 ' , 11 , 762 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gladiator Beast Andabata ' , ' DARK ' , ' Beast-Warrior ' , ' teste158 ' , 12 , 763 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gladiator Beast Essedarii ' , ' EARTH ' , ' Beast ' , ' teste159 ' , 1 , 764 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gladiator Beast Gaiodiaz ' , ' DARK ' , ' Dinosaur ' , ' teste160 ' , 2 , 765 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gladiator Beast Gyzarus ' , ' DARK ' , ' Winged Beast ' , ' teste161 ' , 3 , 766 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gladiator Beast Heraklinos ' , ' FIRE ' , ' Beast-Warrior ' , ' teste162 ' , 4 , 767 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gladiator Beast Nerokius ' , ' DARK ' , ' Winged Beast ' , ' teste163 ' , 5 , 768 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Gladiator Beast Tamer Editor ' , ' DARK ' , ' Beast-Warrior ' , ' teste164 ' , 6 , 769 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Goddess Bow ' , ' LIGHT ' , ' Warrior ' , ' teste165 ' , 7 , 770 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Goyo Emperor ' , ' EARTH ' , ' Warrior ' , ' teste166 ' , 8 , 771 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Great Mammoth of Goldfine ' , ' DARK ' , ' Zombie ' , ' teste167 ' , 9 , 772 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Greedy Venom Fusion Dragon ' , ' DARK ' , ' Dragon ' , ' teste168 ' , 10 , 773 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Humanoid Worm Drake ' , ' WATER ' , ' Aqua ' , ' teste169 ' , 11 , 774 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ignition Beast Volcannon ' , ' EARTH ' , ' Machine ' , ' teste170 ' , 12 , 775 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Imperion Magnum the Superconductive Battlebot ' , ' EARTH ' , ' Rock ' , ' teste171 ' , 1 , 776 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Infernoid Tierra ' , ' FIRE ' , ' Fiend ' , ' teste172 ' , 2 , 777 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Invoked Caliga ' , ' DARK ' , ' Beast ' , ' teste173 ' , 3 , 778 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Invoked Cocytus ' , ' WATER ' , ' Dragon ' , ' teste174 ' , 4 , 779 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Invoked Elysium ' , ' LIGHT ' , ' Fairy ' , ' teste175 ' , 5 , 780 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Invoked Magellanica ' , ' EARTH ' , ' Rock ' , ' teste176 ' , 6 , 781 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Invoked Mechaba ' , ' LIGHT ' , ' Machine ' , ' teste177 ' , 7 , 782 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Invoked Purgatrio ' , ' FIRE ' , ' Fiend ' , ' teste178 ' , 8 , 783 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Invoked Raidjin ' , ' WIND ' , ' Warrior ' , ' teste179 ' , 9 , 784 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Kaiser Dragon ' , ' LIGHT ' , ' Dragon ' , ' teste180 ' , 10 , 785 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Kaminari Attack ' , ' WIND ' , ' Thunder ' , ' teste181 ' , 11 , 786 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Kamionwizard ' , ' DARK ' , ' Spellcaster ' , ' teste182 ' , 12 , 787 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Karbonala Warrior ' , ' EARTH ' , ' Warrior ' , ' teste183 ' , 1 , 788 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' King Dragun ' , ' DARK ' , ' Dragon ' , ' teste184 ' , 2 , 789 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' KoaloKoala ' , ' EARTH ' , ' Beast ' , ' teste185 ' , 3 , 790 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Kwagar Hercules ' , ' EARTH ' , ' Insect ' , ' teste186 ' , 4 , 791 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Labyrinth Tank ' , ' DARK ' , ' Machine ' , ' teste187 ' , 5 , 792 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Lunalight Cat Dancer ' , ' DARK ' , ' Beast-Warrior ' , ' teste188 ' , 6 , 793 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Lunalight Leo Dancer ' , ' DARK ' , ' Beast-Warrior ' , ' teste189 ' , 7 , 794 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Lunalight Panther Dancer ' , ' DARK ' , ' Beast-Warrior ' , ' teste190 ' , 8 , 795 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Lyrilusc  Independent Nightingale ' , ' WIND ' , ' Winged Beast ' , ' teste191 ' , 9 , 796 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Maneating Black Shark ' , ' WATER ' , ' Fish ' , ' teste192 ' , 10 , 797 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Marine Beast ' , ' WATER ' , ' Fish ' , ' teste193 ' , 11 , 798 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Acid ' , ' WATER ' , ' Warrior ' , ' teste194 ' , 12 , 799 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Anki ' , ' DARK ' , ' Warrior ' , ' teste195 ' , 1 , 800 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Blast ' , ' WIND ' , ' Warrior ' , ' teste196 ' , 2 , 801 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Dark Law ' , ' DARK ' , ' Warrior ' , ' teste197 ' , 3 , 802 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Dian ' , ' EARTH ' , ' Warrior ' , ' teste198 ' , 4 , 803 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Divine Wind ' , ' WIND ' , ' Warrior ' , ' teste199 ' , 5 , 804 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Goka ' , ' FIRE ' , ' Warrior ' , ' teste200 ' , 6 , 805 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Koga ' , ' LIGHT ' , ' Warrior ' , ' teste201 ' , 7 , 806 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Masked HERO Vapor ' , ' WATER ' , ' Warrior ' , ' teste202 ' , 8 , 807 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Master of Oz ' , ' EARTH ' , ' Beast ' , ' teste203 ' , 9 , 808 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Mavelus ' , ' WIND ' , ' Winged Beast ' , ' teste204 ' , 10 , 809 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Metal Dragon ' , ' WIND ' , ' Machine ' , ' teste205 ' , 11 , 810 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Metalfoes Adamante ' , ' FIRE ' , ' Psychic ' , ' teste206 ' , 12 , 811 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Metalfoes Crimsonite ' , ' FIRE ' , ' Psychic ' , ' teste207 ' , 1 , 812 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Metalfoes Mithrilium ' , ' FIRE ' , ' Psychic ' , ' teste208 ' , 2 , 813 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Metalfoes Orichalc ' , ' FIRE ' , ' Psychic ' , ' teste209 ' , 3 , 814 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Meteor B Dragon ' , ' FIRE ' , ' Dragon ' , ' teste210 ' , 4 , 815 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Meteor Black Comet Dragon ' , ' DARK ' , ' Dragon ' , ' teste211 ' , 5 , 816 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' MillenniumEyes Restrict ' , ' DARK ' , ' Spellcaster ' , ' teste212 ' , 6 , 817 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Mirror Force Dragon ' , ' LIGHT ' , ' Dragon ' , ' teste213 ' , 7 , 818 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Mokey Mokey King ' , ' LIGHT ' , ' Fairy ' , ' teste214 ' , 8 , 819 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Mudragon of the Swamp ' , ' WATER ' , ' Wyrm ' , ' teste215 ' , 9 , 820 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Multiple Piece Golem ' , ' EARTH ' , ' Rock ' , ' teste216 ' , 10 , 821 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Musician King ' , ' LIGHT ' , ' Spellcaster ' , ' teste217 ' , 11 , 822 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Mystical Sand ' , ' EARTH ' , ' Rock ' , ' teste218 ' , 12 , 823 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Naturia Exterio ' , ' EARTH ' , ' Beast ' , ' teste219 ' , 1 , 824 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Naturia Gaiastrio ' , ' EARTH ' , ' Rock ' , ' teste220 ' , 2 , 825 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Neo BlueEyes Ultimate Dragon ' , ' LIGHT ' , ' Dragon ' , ' teste221 ' , 3 , 826 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' NeoSpacian Marine Dolphin ' , ' WATER ' , ' Warrior ' , ' teste222 ' , 4 , 827 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' NeoSpacian Twinkle Moss ' , ' LIGHT ' , ' Plant ' , ' teste223 ' , 5 , 828 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' OddEyes Venom Dragon ' , ' DARK ' , ' Dragon ' , ' teste224 ' , 6 , 829 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' OddEyes Vortex Dragon ' , ' WIND ' , ' Dragon ' , ' teste225 ' , 7 , 830 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ojama King ' , ' LIGHT ' , ' Beast ' , ' teste226 ' , 8 , 831 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ojama Knight ' , ' LIGHT ' , ' Beast ' , ' teste227 ' , 9 , 832 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Pair Cycroid ' , ' EARTH ' , ' Machine ' , ' teste228 ' , 10 , 833 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Panzer Dragon ' , ' LIGHT ' , ' Machine ' , ' teste229 ' , 11 , 834 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Performapal Gatlinghoul ' , ' DARK ' , ' Fiend ' , ' teste230 ' , 12 , 835 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Performapal OddEyes Metal Claw ' , ' DARK ' , ' Dragon ' , ' teste231 ' , 1 , 836 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Pragtical ' , ' EARTH ' , ' Dinosaur ' , ' teste232 ' , 2 , 837 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Predaplant Chimerafflesia ' , ' DARK ' , ' Plant ' , ' teste233 ' , 3 , 838 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Predaplant Dragostapelia ' , ' DARK ' , ' Plant ' , ' teste234 ' , 4 , 839 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Punished Eagle ' , ' WIND ' , ' Winged Beast ' , ' teste235 ' , 5 , 840 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Rabid Horseman ' , ' EARTH ' , ' Beast-Warrior ' , ' teste236 ' , 6 , 841 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Rainbow Neos ' , ' LIGHT ' , ' Warrior ' , ' teste237 ' , 7 , 842 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Rainbow Overdragon ' , ' LIGHT ' , ' Dragon ' , ' teste238 ' , 8 , 843 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Rare Fish ' , ' WATER ' , ' Fish ' , ' teste239 ' , 9 , 844 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Reaper on the Nightmare ' , ' DARK ' , ' Zombie ' , ' teste240 ' , 10 , 845 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' RedEyes Black Dragon Sword ' , ' DARK ' , ' Dragon ' , ' teste241 ' , 11 , 846 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' RedEyes Slash Dragon ' , ' DARK ' , ' Dragon ' , ' teste242 ' , 12 , 847 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ritual Beast UltiApelio ' , ' WIND ' , ' Pyro ' , ' teste243 ' , 1 , 848 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ritual Beast UltiCannahawk ' , ' WIND ' , ' Thunder ' , ' teste244 ' , 2 , 849 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ritual Beast UltiGaiapelio ' , ' LIGHT ' , ' Psychic ' , ' teste245 ' , 3 , 850 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ritual Beast UltiPettlephin ' , ' WIND ' , ' Aqua ' , ' teste246 ' , 4 , 851 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Roaring Ocean Snake ' , ' WATER ' , ' Aqua ' , ' teste247 ' , 5 , 852 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Rocket Hermos Cannon ' , ' LIGHT ' , ' Warrior ' , ' teste248 ' , 6 , 853 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Rose Spectre of Dunn ' , ' DARK ' , ' Plant ' , ' teste249 ' , 7 , 854 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' RuneEyes Pendulum Dragon ' , ' DARK ' , ' Dragon ' , ' teste250 ' , 8 , 855 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ryu Senshi ' , ' EARTH ' , ' Warrior ' , ' teste251 ' , 9 , 856 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Sanwitch ' , ' DARK ' , ' Spellcaster ' , ' teste252 ' , 10 , 857 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Schuberta the Melodious Maestra ' , ' LIGHT ' , ' Fairy ' , ' teste253 ' , 11 , 858 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Sea Monster of Theseus ' , ' WATER ' , ' Zombie ' , ' teste254 ' , 12 , 859 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Secret Six Samurai  Rihan ' , ' EARTH ' , ' Warrior ' , ' teste255 ' , 1 , 860 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Skelgon ' , ' DARK ' , ' Zombie ' , ' teste256 ' , 2 , 861 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Skull Knight ' , ' DARK ' , ' Spellcaster ' , ' teste257 ' , 3 , 862 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Skull Knight #2 ' , ' DARK ' , ' Spellcaster ' , ' teste258 ' , 4 , 863 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Skullbird ' , ' WIND ' , ' Winged Beast ' , ' teste259 ' , 5 , 864 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Sky Galloping Gaia the Dragon Champion ' , ' WIND ' , ' Dragon ' , ' teste260 ' , 6 , 865 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Soul Hunter ' , ' DARK ' , ' Fiend ' , ' teste261 ' , 7 , 866 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' St Joan ' , ' LIGHT ' , ' Fairy ' , ' teste262 ' , 8 , 867 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Starving Venom Fusion Dragon ' , ' DARK ' , ' Dragon ' , ' teste263 ' , 9 , 868 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Steam Gyroid ' , ' EARTH ' , ' Machine ' , ' teste264 ' , 10 , 869 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Super Robolady ' , ' EARTH ' , ' Machine ' , ' teste265 ' , 11 , 870 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Super Roboyarou ' , ' EARTH ' , ' Machine ' , ' teste266 ' , 12 , 871 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Super Vehicroid  Mobile Base ' , ' EARTH ' , ' Machine ' , ' teste267 ' , 1 , 872 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Super Vehicroid  Stealth Union ' , ' EARTH ' , ' Machine ' , ' teste268 ' , 2 , 873 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Super Vehicroid Jumbo Drill ' , ' EARTH ' , ' Machine ' , ' teste269 ' , 3 , 874 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Superalloy Beast Raptinus ' , ' LIGHT ' , ' Dragon ' , ' teste270 ' , 4 , 875 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Supreme Arcanite Magician ' , ' LIGHT ' , ' Spellcaster ' , ' teste271 ' , 5 , 876 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Supreme King Dragon Starving Venom ' , ' DARK ' , ' Dragon ' , ' teste272 ' , 6 , 877 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Supreme King ZARC ' , ' DARK ' , ' Dragon ' , ' teste273 ' , 7 , 878 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' The Last Warrior from Another Planet ' , ' EARTH ' , ' Warrior ' , ' teste274 ' , 8 , 879 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Thousand Dragon ' , ' WIND ' , ' Dragon ' , ' teste275 ' , 9 , 880 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' ThousandEyes Restrict ' , ' DARK ' , ' Spellcaster ' , ' teste276 ' , 10 , 881 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Timaeus the Knight of Destiny ' , ' LIGHT ' , ' Warrior ' , ' teste277 ' , 11 , 882 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Time Magic Hammer ' , ' LIGHT ' , ' Spellcaster ' , ' teste278 ' , 12 , 883 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Twin Photon Lizard ' , ' LIGHT ' , ' Dragon ' , ' teste279 ' , 1 , 884 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' TwinHeaded Thunder Dragon ' , ' LIGHT ' , ' Thunder ' , ' teste280 ' , 2 , 885 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Tyrant Burst Dragon ' , ' LIGHT ' , ' Dragon ' , ' teste281 ' , 3 , 886 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' UFOroid Fighter ' , ' LIGHT ' , ' Machine ' , ' teste282 ' , 4 , 887 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ultimate Ancient Gear Golem ' , ' EARTH ' , ' Machine ' , ' teste283 ' , 5 , 888 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Ultimate Axon Kicker ' , ' LIGHT ' , ' Psychic ' , ' teste284 ' , 6 , 889 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Vermillion Sparrow ' , ' FIRE ' , ' Pyro ' , ' teste285 ' , 7 , 890 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Vision HERO Adoration ' , ' DARK ' , ' Warrior ' , ' teste286 ' , 8 , 891 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Vision HERO Trinity ' , ' DARK ' , ' Warrior ' , ' teste287 ' , 9 , 892 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' VWTiger Catapult ' , ' LIGHT ' , ' Machine ' , ' teste288 ' , 10 , 893 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' VWXYZDragon Catapult Cannon ' , ' LIGHT ' , ' Machine ' , ' teste289 ' , 11 , 894 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Warrior of Tradition ' , ' EARTH ' , ' Warrior ' , ' teste290 ' , 12 , 895 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Windwitch  Crystal Bell ' , ' WIND ' , ' Spellcaster ' , ' teste291 ' , 1 , 896 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Worm Zero ' , ' LIGHT ' , ' Reptile ' , ' teste292 ' , 2 , 897 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' XYDragon Cannon ' , ' LIGHT ' , ' Machine ' , ' teste293 ' , 3 , 898 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' XYZDragon Cannon ' , ' LIGHT ' , ' Machine ' , ' teste294 ' , 4 , 899 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' XZTank Cannon ' , ' LIGHT ' , ' Machine ' , ' teste295 ' , 5 , 900 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Yasushi the Skull Knight ' , ' DARK ' , ' Spellcaster ' , ' teste296 ' , 6 , 901 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' YZTank Dragon ' , ' LIGHT ' , ' Machine ' , ' teste297 ' , 7 , 902 );
INSERT INTO CARTAS(car_nome, car_atributo, car_tipo, car_desc, car_col_fk,car_id) VALUES ( ' Zombie Warrior ' , ' DARK ' , ' Zombie ' , ' teste298 ' , 8 , 903 );


/*TODO INSERT NORMAL/EFEITO MONSTROS */
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4000 , 4000 , 608 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2800 , 609 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1700 , 1500 , 610 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2400 , 611 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2400 , 612 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2300 , 1800 , 613 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1850 , 1300 , 614 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2900 , 2500 , 615 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1000 , 1800 , 616 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3300 , 3300 , 617 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2250 , 1900 , 618 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3800 , 2500 , 619 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3200 , 2500 , 620 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3500 , 3000 , 621 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 622 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3200 , 2500 , 623 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4000 , 4000 , 624 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1380 , 1530 , 625 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2000 , 626 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2300 , 2000 , 627 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2300 , 628 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1000 , 2000 , 629 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 2000 , 630 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2500 , 631 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4500 , 3800 , 632 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 2000 , 633 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2000 , 634 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2500 , 635 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4500 , 3000 , 636 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1100 , 800 , 637 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1800 , 638 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 639 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 640 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 641 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1600 , 642 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2600 , 643 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4500 , 3000 , 644 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2300 , 1800 , 645 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 800 , 646 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4000 , 2800 , 647 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 1900 , 648 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1800 , 1400 , 649 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2100 , 650 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1000 , 1000 , 651 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 2000 , 652 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 653 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2500 , 654 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2400 , 655 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 1500 , 656 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2000 , 657 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3500 , 3000 , 658 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3200 , 3000 , 659 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2500 , 660 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 1200 , 661 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1500 , 662 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 800 , 663 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 1700 , 664 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2500 , 665 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2900 , 2400 , 666 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1500 , 1250 , 667 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1600 , 668 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 3000 , 669 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 2600 , 670 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 3000 , 671 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2400 , 672 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 2950 , 673 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1500 , 674 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3200 , 2000 , 675 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 5000 , 5000 , 676 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 0 , 677 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1200 , 900 , 678 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2700 , 2000 , 679 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2500 , 680 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2450 , 1950 , 681 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 3000 , 682 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 200 , 2800 , 683 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 800 , 684 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 1200 , 685 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 2200 , 686 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 687 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 688 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 689 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2500 , 690 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2700 , 2200 , 691 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 692 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 1000 , 693 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2500 , 694 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2900 , 2600 , 695 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 696 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1200 , 697 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 698 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 2600 , 699 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 700 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 701 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2200 , 702 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2300 , 1600 , 703 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2500 , 704 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2300 , 705 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1400 , 1000 , 706 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 3000 , 707 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1800 , 708 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 1000 , 709 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 2100 , 710 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1200 , 711 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 2300 , 712 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 2500 , 713 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2100 , 714 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2100 , 715 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1800 , 1000 , 716 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2500 , 717 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2800 , 718 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 719 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 2100 , 720 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 1500 , 721 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 2300 , 722 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 2300 , 723 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1700 , 724 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 725 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 2500 , 726 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1200 , 727 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 1500 , 728 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3500 , 2100 , 729 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 2300 , 730 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 1200 , 731 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2700 , 2000 , 732 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 5000 , 5000 , 733 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1000 , 800 , 734 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1800 , 1600 , 735 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1800 , 1400 , 736 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1800 , 737 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2000 , 738 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2200 , 739 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 3000 , 740 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2000 , 741 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2000 , 742 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 2000 , 743 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1200 , 744 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 1500 , 745 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 746 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 900 , 700 , 747 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3500 , 2800 , 748 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 2100 , 749 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 1200 , 750 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1950 , 2450 , 751 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1400 , 2600 , 752 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1950 , 753 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3400 , 2000 , 754 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 1000 , 755 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2900 , 2500 , 756 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2450 , 1400 , 757 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 1300 , 758 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2300 , 1400 , 759 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1800 , 1800 , 760 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2900 , 2500 , 761 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1850 , 1500 , 762 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1000 , 2800 , 763 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 1400 , 764 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 1500 , 765 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 1500 , 766 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2800 , 767 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 1900 , 768 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 3000 , 769 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1500 , 1600 , 770 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3300 , 2500 , 771 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1800 , 772 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3300 , 2500 , 773 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 2000 , 774 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2300 , 1600 , 775 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4000 , 4000 , 776 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3400 , 3600 , 777 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1000 , 1800 , 778 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1800 , 2900 , 779 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3200 , 4000 , 780 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 3300 , 781 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2100 , 782 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2300 , 2000 , 783 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 2400 , 784 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2300 , 2000 , 785 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1400 , 786 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1300 , 1100 , 787 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1500 , 1200 , 788 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 1100 , 789 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 200 , 790 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1700 , 791 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2400 , 792 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2000 , 793 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3500 , 3000 , 794 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2500 , 795 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1000 , 0 , 796 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1300 , 797 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1700 , 1600 , 798 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 2100 , 799 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 1200 , 800 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1800 , 801 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 1800 , 802 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 3000 , 803 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2700 , 1900 , 804 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1800 , 805 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 1800 , 806 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2000 , 807 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4200 , 3700 , 808 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1300 , 900 , 809 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1850 , 1700 , 810 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2500 , 811 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 3000 , 812 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 1000 , 813 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2200 , 814 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3500 , 2000 , 815 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3500 , 2000 , 816 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 817 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 1200 , 818 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 300 , 100 , 819 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1600 , 820 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 1300 , 821 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1750 , 1500 , 822 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1700 , 823 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2400 , 824 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3200 , 2100 , 825 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4500 , 3800 , 826 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 900 , 1100 , 827 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 500 , 1100 , 828 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3300 , 2500 , 829 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 3000 , 830 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 3000 , 831 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 2500 , 832 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1600 , 1200 , 833 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1000 , 2600 , 834 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2900 , 900 , 835 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2000 , 836 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1500 , 837 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 838 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2700 , 1900 , 839 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1800 , 840 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 1700 , 841 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4500 , 3000 , 842 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4000 , 0 , 843 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1500 , 1200 , 844 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 800 , 600 , 845 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2000 , 846 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2400 , 847 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 400 , 848 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1400 , 1600 , 849 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3200 , 2100 , 850 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 200 , 2800 , 851 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1800 , 852 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1500 , 1300 , 853 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 1800 , 854 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2000 , 855 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 1200 , 856 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 1800 , 857 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2000 , 858 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1800 , 859 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2400 , 860 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1700 , 1900 , 861 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2650 , 2250 , 862 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2650 , 2250 , 863 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1700 , 864 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2600 , 2100 , 865 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1800 , 866 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2000 , 867 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2000 , 868 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1600 , 869 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1200 , 500 , 870 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1200 , 500 , 871 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 5000 , 872 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3600 , 3000 , 873 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2000 , 874 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 2200 , 875 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1400 , 2800 , 876 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2000 , 877 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4000 , 4000 , 878 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2350 , 2300 , 879 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2000 , 880 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 881 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 882 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 500 , 400 , 883 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 1000 , 884 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2100 , 885 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2900 , 2500 , 886 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 887 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 4400 , 3400 , 888 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2900 , 1700 , 889 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1500 , 890 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2100 , 891 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2500 , 2000 , 892 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2000 , 2100 , 893 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 3000 , 2800 , 894 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1900 , 1700 , 895 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2400 , 896 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 0 , 0 , 897 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2200 , 1900 , 898 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2800 , 2600 , 899 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2400 , 2100 , 900 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2650 , 2250 , 901 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 2100 , 2200 , 902 );
INSERT INTO MONSTROS(mon_atk, mon_def, mon_car_id) VALUES ( 1200 , 900 , 903 );


/*TODO - INSERT ESTRELAS */
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 608 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 609 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 610 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 611 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 612 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 613 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 614 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 615 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 616 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 617 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 618 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 619 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 620 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 621 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 622 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 623 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 624 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 625 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 626 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 627 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 628 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 629 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 630 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 631 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 632 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 633 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 634 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 635 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 636 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 3 , 637 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 638 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 639 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 640 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 641 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 642 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 643 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 644 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 645 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 646 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 647 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 648 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 649 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 650 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 651 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 652 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 653 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 654 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 655 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 656 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 657 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 658 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 659 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 660 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 661 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 662 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 663 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 664 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 665 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 666 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 667 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 668 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 669 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 670 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 671 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 672 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 673 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 674 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 675 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 676 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 677 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 3 , 678 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 679 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 680 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 681 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 682 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 683 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 684 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 685 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 686 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 687 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 688 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 689 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 690 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 691 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 692 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 693 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 694 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 695 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 696 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 697 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 698 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 699 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 700 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 701 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 702 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 703 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 704 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 705 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 706 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 707 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 708 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 709 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 710 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 711 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 712 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 713 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 714 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 715 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 716 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 717 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 718 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 719 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 720 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 721 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 722 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 723 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 724 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 725 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 726 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 727 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 728 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 729 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 730 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 731 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 732 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 733 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 3 , 734 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 735 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 736 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 737 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 738 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 739 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 740 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 741 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 742 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 743 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 744 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 745 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 1 , 746 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 3 , 747 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 748 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 749 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 750 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 751 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 752 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 753 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 754 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 755 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 756 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 757 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 758 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 759 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 760 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 761 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 762 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 763 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 764 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 765 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 766 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 767 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 768 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 769 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 770 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 771 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 772 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 773 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 774 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 775 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 776 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 11 , 777 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 778 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 779 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 780 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 781 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 782 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 783 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 784 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 785 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 786 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 787 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 788 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 789 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 790 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 791 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 792 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 793 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 794 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 795 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 1 , 796 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 797 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 798 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 799 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 800 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 801 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 802 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 803 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 804 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 805 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 806 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 807 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 808 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 809 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 810 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 811 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 812 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 813 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 814 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 815 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 816 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 1 , 817 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 818 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 819 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 820 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 821 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 822 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 823 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 824 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 825 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 826 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 827 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 828 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 829 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 830 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 831 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 832 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 833 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 834 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 835 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 836 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 837 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 838 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 839 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 840 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 841 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 842 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 843 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 844 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 845 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 846 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 847 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 848 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 849 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 850 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 851 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 852 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 4 , 853 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 854 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 855 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 856 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 857 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 858 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 859 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 860 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 861 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 862 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 863 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 864 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 865 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 866 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 867 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 868 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 869 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 870 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 871 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 872 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 9 , 873 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 874 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 875 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 876 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 877 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 12 , 878 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 879 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 880 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 1 , 881 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 882 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 2 , 883 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 884 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 885 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 886 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 887 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 888 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 889 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 5 , 890 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 891 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 892 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 893 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 894 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 895 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 896 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 10 , 897 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 898 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 8 , 899 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 900 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 7 , 901 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 6 , 902 );
INSERT INTO NML_MONSTROS(nml_estrelas,nml_mon_id) VALUES ( 3 , 903 );
