
DROP SEQUENCE SEQ_CLI ;
DROP SEQUENCE SEQ_PDT ;
DROP SEQUENCE SEQ_SLV ;
DROP SEQUENCE SEQ_PLT ;
DROP SEQUENCE SEQ_COL ;
DROP SEQUENCE SEQ_CAR ;
DROP SEQUENCE SEQ_MAG ;
DROP SEQUENCE SEQ_MON ;
DROP SEQUENCE SEQ_XYZ ;
DROP SEQUENCE SEQ_NML ;
DROP SEQUENCE SEQ_PEN ;
